name: hidden_room_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  dart_frog_web_socket: ^0.1.0-dev.3
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.3
  json_serializable: ^6.6.2
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
